Repository awsaf49/gcvit-tf, pull requests merged in 2023-05, with the labels that each got.

#9 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#12 Deprecated TFA + moved all necessary classes/methods into gcvit
  README.md
  gcvit/__init__.py
  gcvit/layers/__init__.py
  gcvit/layers/feature.py
  gcvit/layers/pooling.py
  gcvit/utils/__init__.py
  gcvit/utils/conv_utils.py
  requirements.txt
Labels: enhancement

#14 Added simple unit tests in tests CI
  .github/workflows/tests.yml
  app.py
  gcvit/version.py
  tests/__init__.py
  tests/test_gcvit.py
Labels: enhancement

#16 update kaggle params for gcvit
  gcvit/models/gcvit.py
Labels: bug
